add centos version

diff --git a/.github/workflows/dev-ci.yml b/.github/workflows/dev-ci.yml
--- a/.github/workflows/dev-ci.yml
+++ b/.github/workflows/dev-ci.yml
@@ -81,3 +81,63 @@ jobs:
         with:
           name: sirius-solver-install-ubuntu-${{ env.SIRIUS_VERSION }}
           path: sirius-artifact
+
+  dev_centos7:
+    name: Build Sirius on CentOS7
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+
+      - name: Build the Docker image
+        run: |
+          docker build -t centos7withcmake:latest $GITHUB_WORKSPACE --file $GITHUB_WORKSPACE/.github/workflows/docker/Dockerfile
+
+      - name: Run build steps in Docker container
+        run: |
+          docker run --name build_container -v $GITHUB_WORKSPACE:/workspace centos7withcmake:latest /bin/bash -c "
+            cd /workspace
+
+            # Define environment variables
+            export SIRIUS_INSTALL_DIR=centos7_sirius-solver-install
+            export SIRIUS_INSTALL_PATH="/workspace/$SIRIUS_INSTALL_DIR"
+            export ARCHIVE_NAME="centos7_sirius-solver.zip"
+            export ARCHIVE_PATH="/workspace/$ARCHIVE_NAME"
+            
+            # Configuration
+            cmake -S src -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$SIRIUS_INSTALL_DIR"
+            
+            # Compilation and installation
+            cmake --build build --config Release -j14
+            cmake --install build
+            
+            # Extraction of Sirius version
+            CONFIG_FILE="build/CPackConfig.cmake"
+            if [ ! -f "$CONFIG_FILE" ]; then
+              echo "Error: CPackConfig.cmake not found. Make sure CMake configuration and build were successful."
+              exit 1
+            fi
+            
+            MAJOR=$(grep 'set(CPACK_PACKAGE_VERSION_MAJOR' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
+            MINOR=$(grep 'set(CPACK_PACKAGE_VERSION_MINOR' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
+            PATCH=$(grep 'set(CPACK_PACKAGE_VERSION_PATCH' "$CONFIG_FILE" | sed -E 's/.*"([0-9]+)".*/\1/')
+            VERSION="$MAJOR.$MINOR.$PATCH"
+            
+            # Prepare upload
+            mkdir -p sirius-artifact
+            mv "$SIRIUS_INSTALL_DIR" sirius-artifact/
+            
+            # Save Sirius version
+            echo "SIRIUS_VERSION=$VERSION" >> /workspace/sirius_version.txt
+          "
+
+      - name: Retrieve Sirius version
+        run: |
+          echo "SIRIUS_VERSION=$(cat sirius_version.txt)" >> $GITHUB_ENV
+
+      - name: Upload Sirius archive
+        if: github.event_name == 'workflow_dispatch' && inputs.generate_artifacts == 'true'
+        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # 4.6.2
+        with:
+          name: sirius-solver-install-centos7-${{ env.SIRIUS_VERSION }}
+          path: sirius-artifact
